### ISSUE TITLE
test

### ISSUE THREAD

**Issue by bramtayl** [bramtayl/RegularExpressions.jl#2]
@JuliaRegistrator register()

**Comment by bramtayl** [comment]
@nkottary sorry to bother you but you seem to be doing work on JuliaRegistrator, can you tell me what I'm doing wrong?

**Comment by nkottary** [comment]
You've misspelt version as verion in your Project.toml

**Comment by bramtayl** [comment]
@JuliaRegistrator register()

**Comment by bramtayl** [comment]
doh. thanks!

**Comment by bramtayl** [comment]
@JuliaRegistrator register()
